site_name: Requests III
site_description:  Requests is an elegant and simple HTTP library for Python, built for human beings.

theme:
    name: 'alabaster'
    custom_dir: 'docs-theme'

repo_name: encode/http3
repo_url: https://github.com/encode/http3
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - QuickStart: 'quickstart.md'
    - Advanced Usage: 'advanced.md'
    - Parallel Requests: 'parallel.md'
    - Async Client: 'async.md'
    - Requests Compatibility: 'compatibility.md'
    - Developer Interface: 'api.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: "¶"

extra:
  logo: img/requests-sidebar.png
  logo_title: Requests
  show_powered_by: False
  homepage_nav: False
